### ISSUE TITLE
Help not showing Extensions -> Layers menu from projects -> Help

### ISSUE THREAD

**Issue by nicogodet** [aeag/MenuFromProject-Qgis-Plugin#53]
QGIS 3.24.0 & 3.22.4
Win10

Plugin version 2.0.2

**Comment by xcaeag** [comment]
a problem it seems in the 'utils' module of QGis.
The showPluginHelp function mixes '/' and '\', and the Qt Url produced is invalid, under windows.

**Comment by xcaeag** [comment]
corrected in version 2.0.3 of the plugin, while waiting for a QGis API patch.

**Comment by nicogodet** [comment]
It seems that it does not fix the issue properly...

Using QUrl.fromLocalFile works fine.
